package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"encore.app/graphql/generated"
	"encore.app/graphql/model"
	"encore.app/ledger"
)

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (*model.MutationResult, error) {
	ledger.CreateNewAccount(ctx, &ledger.CreateNewAccountParams{AccountId: input.ID, Amount: uint64(input.InitialAmount)})

	return &model.MutationResult{Status: 0}, nil
}

// Authorize is the resolver for the authorize field.
func (r *mutationResolver) Authorize(ctx context.Context, input model.AuthorizeInput) (*model.MutationResult, error) {
	ledger.Authorize(ctx, &ledger.AuthorizeParams{
		Amount:    uint64(input.Amount),
		AccountId: input.AccountID,
	})

	return &model.MutationResult{Status: 0}, nil
}

// Present is the resolver for the present field.
func (r *mutationResolver) Present(ctx context.Context, input model.PresentInput) (*model.MutationResult, error) {
	ledger.Present(ctx, &ledger.PresentParams{
		Amount:    uint64(input.Amount),
		AccountId: input.AccountID,
	})

	return &model.MutationResult{Status: 0}, nil
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context, input model.AccountsInput) ([]*model.Account, error) {
	//client, _ := db.Get(ctx)
	//
	//uint128Ids := make([]tb_types.Uint128, len(input.AccountID))
	//
	//for i, id := range input.AccountID {
	//	uint128Ids[i], _ = tb_types.HexStringToUint128(*id)
	//}
	//
	//accounts, err := (*client).LookupAccounts(uint128Ids)
	//
	//if err != nil {
	//	log.Println("Can' take accoutns for ids", input.AccountID)
	//	return nil, nil
	//}
	//
	//models := make([]*model.Account, 0)
	//
	//for _, account := range accounts {
	//	model := ledger.SerializeToModel(&account)
	//	models = append(models, &model)
	//}
	//
	//log.Println(models)

	return nil, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
